In [1]:
from fileinput import filename
import pandas as pd

# funcion  head permite ver las primeras 13 filas de mi df
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

df = pd.read_csv('../data/pima-indians-diabetes.csv', names=names)

df.head(13)

# ---------
# filename = '../data/pima-indians-diabetes.csv'
# name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
# data = pd.read_csv(filename, names=name)

# print(data.head(13))

    preg  plas  pres  skin  test  mass    pedi  age  class
0      6   148    72    35     0  33.6   627.0   50      1
1      1    85    66    29     0  26.6   351.0   31      0
2      8   183    64     0     0  23.3   672.0   32      1
3      1    89    66    23    94  28.1   167.0   21      0
4      0   137    40    35   168  43.1  2288.0   33      1
5      5   116    74     0     0  25.6   201.0   30      0
6      3    78    50    32    88  31.0   248.0   26      1
7     10   115     0     0     0  35.3   134.0   29      0
8      2   197    70    45   543  30.5   158.0   53      1
9      8   125    96     0     0   0.0   232.0   54      1
10     4   110    92     0     0  37.6   191.0   30      0
11    10   168    74     0     0  38.0   537.0   34      1
12    10   139    80     0     0  27.1  1441.0   57      0

In [2]:
# imprime las dimensiones de mi df
# print(df.shape)
df.shape

(768, 9)

In [3]:
# imprime los tipos de datos de mi df; dara pistas sobre que tipo de algoritmo de ML usar
df.dtypes
# preg (Pregnancies) - numero de embarazos que ha tenido la paciente.
# plas (Plasma Glucose)- concentracion de glucosa en plasma, utilizada para evaluar niveles de azucar en sangre.
# pres (Blood Pressure)- presión arterial diastólica medida en mm Hg.
# skin (Skin Thickness)- grosor del pliegue cutáneo del tríceps en milímetros, relacionado con la grasa corporal.
# test (Insulin)- nivel de insulina sérica en sangre.
# mass (BMI - Body Mass Index)- índice de masa corporal, calculado a partir del peso y la altura.
# pedi (Diabetes Pedigree Function)- indicador que refleja la probabilidad de diabetes según antecedentes familiares.
# age (Age)- edad de la paciente en años.
# class - indica si la paciente tiene diabetes (1) o no (0).

preg       int64
plas       int64
pres       int64
skin       int64
test       int64
mass     float64
pedi     float64
age        int64
class      int64
dtype: object

In [4]:
# muestra las estadisticas de mi df -> cantidad de valores no nulos, media, desviacion estandar, minimo, primer cuartil(25% de los datos debajo del 25), segundo cuartil(50), tercer cuartil(75),  maximo, 
df.describe()

# El conjunto de datos contiene 768 registros y 9 variables. La edad promedio de las pacientes es de 33 años, con edades entre 21 y 81 años. En promedio, las pacientes han tenido 3.8 embarazos.

# La concentración media de glucosa (plas) es de 120.89, mientras que el índice de masa corporal (mass) presenta un promedio de 31.99, lo que indica que gran parte de la población se encuentra en rangos de sobrepeso u obesidad.

# La variable objetivo (class) tiene una media de 0.349, lo que significa que aproximadamente 35 % de las pacientes presentan diabetes y 65 % no la presentan.

# Además, se observan valores mínimos de 0 en variables como glucosa, presión arterial, grosor de piel, insulina e IMC, lo cual es imporbable en un paciente real

,preg,plas,pres,skin,test,mass,pedi,age,class
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,428.235091,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,340.485655,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.100000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,205.000000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,337.000000,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,591.500000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2329.000000,81.000000,1.000000

In [5]:
# dsitribucion de clase -> sirve para ver la cantidad de datos de cada clase
df.groupby('class').size()

# grafica de barras
# df.groupby('class').size().plot(kind='bar')

class
0    500
1    268
dtype: int64

In [6]:
# correlaciones -> se usa para definir relaciones entre pares de atributos numericos, (pearson = relacion lineal)
df.corr(method='pearson')

# correlations = data.corr(method='pearson')
# print(correlations)

# 1->correlacion positiva perfecta
# 0.8->correlacion positiva fuerte
# 0	-> Sin relacion lineal
# -0.8 -> correlacion negativa fuerte
# -1 -> correlacion negativa perfecta

,preg,plas,pres,skin,test,mass,pedi,age,class
preg,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.026205,0.544341,0.221898
plas,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.133163,0.263514,0.466581
pres,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.051436,0.239528,0.065068
skin,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.154274,-0.113970,0.074752
test,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185207,-0.042163,0.130548
mass,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.103575,0.036242,0.292695
pedi,-0.026205,0.133163,0.051436,0.154274,0.185207,0.103575,1.000000,0.017970,0.176608
age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.017970,1.000000,0.238356
class,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.176608,0.238356,1.000000

In [7]:
# asimetria -> indica si los datos estan cargados hacia un lado de la distribucion
df.skew()

# Entre -0.5 y 0.5	aproximadamente simetrica
# Entre -1 y -0.5 o 0.5 y 1	moderadamente asimetrica
# Menor que -1 o mayor que 1	fuertemente asimetrica

preg     0.901674
plas     0.173754
pres    -1.843608
skin     0.109372
test     2.272251
mass    -0.428982
pedi     1.561978
age      1.129597
class    0.635017
dtype: float64