In [ ]:
from fileinput import filename
import pandas as pd

# funcion  head permite ver las primeras 13 filas de mi df
df = pd.read_csv('../data/marmara2.csv', )

df.head(13)

# ---------
# filename = '../data/pima-indians-diabetes.csv'
# data = pd.read_csv(filename, names=name)

# print(data.head(13))

,total_length_cm,body_depth_cm,body_width_cm,head_length_cm,eye_diameter_mm,weight_gr,species
0,7.9,1.2,0.5,1.9,2.2,3.2,Hamsi
1,13.7,2.1,1.0,2.9,3.4,15.0,Hamsi
2,18.5,3.8,1.9,4.4,4.9,47.9,Sardalya
3,12.1,2.3,1.1,3.0,3.7,15.7,İstavrit
4,7.6,1.4,0.6,1.8,1.9,3.5,İstavrit
5,10.5,2.6,1.1,2.5,2.5,12.7,Tekir
6,6.6,1.2,0.5,1.8,2.1,2.1,Mezgit
7,10.0,2.2,0.9,2.2,2.6,6.9,Sardalya
8,7.6,1.3,0.6,1.7,1.8,2.2,Hamsi
9,10.0,1.5,0.7,2.3,3.1,5.4,Hamsi
10,14.8,1.9,0.8,2.9,3.3,22.1,Hamsi
11,18.9,4.6,2.0,4.8,5.0,46.3,Lüfer
12,6.2,0.8,0.4,1.5,2.0,1.5,Hamsi

In [ ]:
# imprime las dimensiones de mi df
# print(df.shape)
df.shape

# el dataframe contiene 1760 filas y 7 columnas

(1760, 7)

In [ ]:
# imprime los tipos de datos de mi df; data pistas sobre que tipo de algoritmo de ML usar
df.dtypes

# # total_length_cm (Longitud total): longitud completa del pez medida en centímetros, desde la cabeza hasta la cola.
# # body_depth_cm (Profundidad del cuerpo): altura máxima del cuerpo del pez en centímetros.
# # body_width_cm (Ancho del cuerpo): ancho o grosor del cuerpo del pez en centímetros.
# # head_length_cm (Longitud de la cabeza): distancia desde la punta del hocico hasta el final de la cabeza, medida en centímetros.
# # eye_diameter_mm (Diámetro del ojo): tamaño del ojo del pez medido en milímetros.
# # weight_gr (Peso): peso del pez expresado en gramos.
# # species (Especie): variable categ0rica que indica la especie a la que pertenece cada pez. Puede utilizarse como variable objetivo o clase para clasificación.

total_length_cm    float64
body_depth_cm      float64
body_width_cm      float64
head_length_cm     float64
eye_diameter_mm    float64
weight_gr          float64
species                str
dtype: object

In [ ]:
# muestra las estadisticas de mi df -> cantidad de valores no nulos, media, desviacion estandar, minimo, primer cuartil(25% de los datos debajo del 25), segundo cuartil(50), tercer cuartil(75),  maximo, 
df.describe()

# este dataset contiene 1760 registros
# La longitud total (total_length_cm) tiene un promedio de 18.27 cm, con valores que van desde 4.5 cm hasta 76.5 cm, mostrando una gran variabilidad en el tamaño de los peces.

# La profundidad corporal (body_depth_cm) presenta una media de 4.01 cm, mientras que la anchura corporal (body_width_cm) tiene un promedio de 1.60 cm. Estas medidas permiten describir la forma del cuerpo de los pescados :3

# La longitud de la cabeza (head_length_cm) tiene un promedio de 4.40 cm, con valores entre 1.0 cm y 21.7 cm. Por otro lado, el diametro del ojo (eye_diameter_mm) presenta una media de 4.76 mm, variando entre 1.1 mm y 15.1 mm.

# Respecto al peso (weight_gr), el promedio es de 180.35 gramos, aunque existe una gran dispersión de los datos, ya que hay pesos entre 0.5 g y 10,127.5 g. eso significaque haypeces considerablemente mas grandes y pesados que la mayoría de los ejemplares.

,total_length_cm,body_depth_cm,body_width_cm,head_length_cm,eye_diameter_mm,weight_gr
count,1760.000000,1760.000000,1760.000000,1760.000000,1760.000000,1760.000000
mean,18.266364,4.013182,1.598977,4.409943,4.759091,180.354318
std,11.670193,5.452095,1.277616,3.097722,2.478672,684.209992
min,4.500000,0.700000,0.300000,1.000000,1.100000,0.500000
25%,11.375000,1.900000,0.800000,2.600000,3.000000,10.575000
50%,15.300000,2.750000,1.200000,3.400000,4.100000,25.000000
75%,20.000000,4.200000,1.800000,5.000000,5.800000,68.375000
max,76.500000,60.800000,9.000000,21.700000,15.100000,10127.500000

In [ ]:
# dsitribucion de clase -> sirve para ver la cantidad de datos de cada clase
df.groupby('species').size()

# grafica de barras
# df.groupby('species').size().plot(kind='bar')


# La distribución de especies muestra que la especie más frecuente es Hamsi con 500 registros, mientras que Izmarit es la menos representada con 80 registros

species
Hamsi       500
Kalkan       30
Lüfer        80
Mezgit      150
Palamut     120
Sardalya    300
Tekir       100
Zargana      50
İstavrit    350
İzmarit      80
dtype: int64

In [ ]:
# correlaciones -> se usa para definir relaciones entre pares de atributos numericos, (pearson = relacion lineal)
df.select_dtypes(include='number').corr(method='pearson')

# correlations = data.corr(method='pearson')
# print(correlations)

# 1->correlacion positiva perfecta
# 0.8->correlacion positiva fuerte
# 0	-> Sin relacion lineal
# -0.8 -> correlacion negativa fuerte
# -1 -> correlacion negativa perfecta


# total_length_cm y head_length_cm = 0.981

# Existe una correlación positiva muy fuerte. Los peces con mayor longitud total tienden a tener cabezas mas largas

# total_length_cm y eye_diameter_mm = 0.932

# También existe una correlación positiva muy fuerte. Los peces más largos suelen tener ojos de mayor tamaño

# body_depth_cm y weight_gr = 0.902

# Es una de las correlaciones mas altas. Los peces con mayor profundidad corporal tienden a ser mas pesados

# body_width_cm y total_length_cm = 0.851

# Los peces mas largos suelen presentar una mayor anchura corporal

# eye_diameter_mm y weight_gr = 0.535
# Existe una correlacion positiva moderada. Los peces con ojos de mayor tamaño tienden a ser mas pesados, aunque esta relacion no es tan fuerte como en otros casos

,total_length_cm,body_depth_cm,body_width_cm,head_length_cm,eye_diameter_mm,weight_gr
total_length_cm,1.000000,0.676050,0.851461,0.981028,0.932015,0.699304
body_depth_cm,0.676050,1.000000,0.666988,0.652312,0.537166,0.901878
body_width_cm,0.851461,0.666988,1.000000,0.762979,0.791972,0.692010
head_length_cm,0.981028,0.652312,0.762979,1.000000,0.931717,0.657353
eye_diameter_mm,0.932015,0.537166,0.791972,0.931717,1.000000,0.535336
weight_gr,0.699304,0.901878,0.692010,0.657353,0.535336,1.000000

In [ ]:
# asimetria -> indica si los datos estan cargados hacia un lado de la distribucion
df.select_dtypes(include='number').skew()

# Entre -0.5 y 0.5	aproximadamente simetrica
# Entre -1 y -0.5 o 0.5 y 1	moderadamente asimetrica
# Menor que -1 o mayor que 1	fuertemente asimetrica

# eye_diameter_mm (1.31) presenta una asimetría positiva, la mayoria de los peces tienen diametros de ojo relativamente pequeños, pero existen algunos ejemplares con ojos considerablemente mas grandes.
# total_length_cm (2.14), body_width_cm (2.59) y head_length_cm (2.33) muestran una asimetría positiva fuerte, esto indica que la mayor parte de los peces tiene tamaños moderados, mientras que unos pocos ejemplares son mucho más grandes que el resto.

total_length_cm    2.137856
body_depth_cm      6.649683
body_width_cm      2.591574
head_length_cm     2.331650
eye_diameter_mm    1.310361
weight_gr          7.792198
dtype: float64